languageCode = "en"
languageName = "English"
weight = 1
title = "Welcome to MathSoc"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "Monday, 2 January, 3:04pm"
logo = "mathsoc-banner.png"
secondaryLogo = "mathsoc-banner-darkmode.png"
description = "Univerisity of Edinburgh maths society website"
