[[main]]
name = "Socials"
pre = "heart"
pageRef = "socials"
identifier = "HFCeOk4GzU"
weight = 2

[[main]]
name = "Academics"
pre = "graduation-cap"
pageRef = "academics"
identifier = "n4yUdYZ7Up"
weight = 3

[[main]]
name = "Committee"
pre = "star"
pageRef = "committee"
identifier = "XqJiZj5cbk"
weight = 6

[[main]]
name = "Sports"
pre = "dribbble"
pageRef = "sports"
identifier = "qsRhQjdLlj"
weight = 4

[[main]]
name = "Problems"
pre = "pencil"
pageRef = "problems"
identifier = "Z1QeQj4GzU"
weight = 5

[[main]]
pre = "instagram"
url = "https://www.instagram.com/edinmathsoc/"
identifier = "Y0ec4jFf6f"
weight = 9999

[[footer]]
none = "none"
