[[main]]
name = "Socials"
pre = "heart"
pageRef = "socials"
identifier = "HFCeOk4GzU"
weight = 2

[[main]]
name = "Academics"
pre = "graduation-cap"
pageRef = "academics"
identifier = "n4yUdYZ7Up"
weight = 3

[[main]]
name = "Committee"
pre = "star"
pageRef = "committee"
identifier = "XqJiZj5cbk"
weight = 6

[[main]]
name = "Sports"
pre = "dribbble"
pageRef = "sports"
identifier = "qsRhQjdLlj"
weight = 4

[[main]]
name = "Problems"
pre = "pencil"
pageRef = "problems"
identifier = "Z1QeQj4GzU"
weight = 5

[[main]]
name = "Annual"
pre = "pencil"
pageRef = "annuallecture"
identifier = "Z1QeQj4Gxg"
weight = 6

[[footer]]
none = "none"

[[footer]]
pre = "instagram"
url = "https://www.instagram.com/edinmathsoc/"
identifier = "23hXPYuChi"
weight = 9999


[[footer]]
pre = "link"
pageRef = "links.md"
identifier = "Muj21pBjhy"
weight = 9999

[[footer]]
pre = "github"
url = "https://github.com/samuelwebb2/mathsoc-website"
identifier = "Y0ec4jFf6f"
weight = 9999