[[main]]
name = "Socials"
pre = "heart"
pageRef = "socials"
identifier = "HFCeOk4GzU"
weight = 2

[[main]]
name = "Academics"
pre = "graduation-cap"
pageRef = "academics"
identifier = "n4yUdYZ7Up"
weight = 3

[[main]]
name = "Committee"
pre = "star"
pageRef = "committee"
identifier = "XqJiZj5cbk"
weight = 6

[[main]]
name = "Sports"
pre = "dribbble"
pageRef = "sports"
identifier = "qsRhQjdLlj"
weight = 4

[[footer]]
none = "none"
